package com.bank.bian.legalservices;

import io.swagger.v3.oas.models.OpenAPI;
import io.swagger.v3.oas.models.info.Info;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.annotation.Bean;

/**
 * BIAN Service Domain: Legal Services
 *
 * Business Area:      Business Support
 * Business Domain:    Corporate Services
 * Functional Pattern: Provide Advice
 * Asset Type:         Legal Matter
 * Control Record:     Legal Matter Advisory Session
 *
 * Generated by the bian-platform service generator (Phase 1 — shallow build).
 * Replace the in-memory store with real persistence and domain logic in Phase 2.
 */
@SpringBootApplication
public class Application {

    public static void main(String[] args) {
        SpringApplication.run(Application.class, args);
    }

    @Bean
    public OpenAPI openApi() {
        return new OpenAPI().info(new Info()
                .title("Legal Services — BIAN Semantic API")
                .description("Service Domain 'Legal Services' (Provide Advice pattern) "
                        + "operating on the 'Legal Matter Advisory Session' control record.")
                .version("0.1.0"));
    }
}
